# .sops.yaml
keys:
  - &primary age16vgs27spqfzzkvryyh78lnwj6k6ktn8a2kn69nfqrqzywjdzu5vqjzel5u

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *primary