# .sops.yaml
keys:
  - &primary age1y4artctj5ejhdxyzc8ttxjd5gwq2c5gydx5lfs3nsrz5w27cug5s9fp28l
  - &secondary age17khgylv28qg5we66jxsju2ctqylzvuvvsvxxtgn4afdjz8lzy42slzeq08

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *primary
          - *secondary
