# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  inputs,
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}:
{
  imports = [
    inputs.disko.nixosModules.disko
    ./disk-configuration.nix

    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # default 50% ram
  zramSwap = {
    enable = true;
    priority = 100;
  };

  # https://github.com/sched-ext/scx/blob/main/INSTALL.md#nix
  services.scx = {
    enable = true;
    # scheduler = "scx_lavd"; # default is "scx_rustland"
  };

  boot = {
    kernelPackages = pkgs.cachyosKernels.linuxPackages-cachyos-latest-x86_64-v3;
    supportedFilesystems = [ "ntfs" ];
    initrd.systemd.enable = true;

    kernelParams = [
      "systemd.show_status=auto"
      "intel_pstate=active"
    ];
    kernel.sysctl = {
      "net.core.default_qdisc" = "fq";
      "net.ipv4.tcp_congestion_control" = "bbr";
    };

    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "usbhid"
      "usb_storage"
      "sd_mod"
    ];

    kernelModules = [
      "kvm-intel"
      "fuse"
      "v4l2loopback"
      "nvme"
    ];
    initrd.kernelModules = [ ]; # "nvme"
    extraModulePackages = with config.boot.kernelPackages; [
      v4l2loopback
    ];
  };

  # nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # Hardware optimized compilation
  # https://nixos.wiki/wiki/Build_flags
  nix.settings.system-features = [
    "gccarch-x86-64-v3"
    "gccarch-x86-64-v2"
    "gccarch-x86-64"
  ];
  nixpkgs.localSystem = {
    gcc.arch = "x86-64-v3";
    gcc.tune = "generic";
    system = "x86_64-linux";
  };

  services.thermald.enable = true;

  # List packages system hardware configuration
  hardware = {
    # CPU (Intel/Ryzen) luchshe kupi ryzen: https://www.youtube.com/watch?v=GOkm2C0rk-w
    # GPU (Nvidia)
    nvidia = {
      open = true;
      package = config.boot.kernelPackages.nvidiaPackages.latest;
    };
    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [
        intel-media-driver # For Broadwell (2014) or newer processors (includes 10th Gen)
        intel-vaapi-driver # Optional, for older applications
        vpl-gpu-rt # For modern QSV
        libvdpau
        libva-vdpau-driver
        vulkan-validation-layers
      ];
    };
    cpu.intel.updateMicrocode = true;
  };
}
